openapi: 3.0.0
info:
  version: 0.0-oas3
  title: Heart Failure Prediction
  description: >-
          Predict whether someone will die from heart failure
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Blake Dunaway
  license:
    name: Apache
paths:
  /prediction/{id}:
    get:
      tags:
        - predict
      operationId: python_dir.mypred.heartpred
      description: Returns results from data inputs
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: array
            items:
              type: number
            minItems: 1
          style: simple
          explode: true
        - in: query
          name: metadata
          schema:
            type: boolean
      responses:
        '200':
          description: 'Prediction'
servers:
  - url: 'http://localhost:8080/E222'
components:
  schemas:
    CPU:
      type: object
      required:
        - model
      properties:
        model:
          type: string
    OS:
      type: object
      required:
        - model
      properties:
        model:
          type: string
